/* Generated By:JavaCC: Do not edit this line. PseudoConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PseudoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TNull = 1;
  /** RegularExpression Id. */
  int TSelf = 2;
  /** RegularExpression Id. */
  int TSqrt = 3;
  /** RegularExpression Id. */
  int TCeil = 4;
  /** RegularExpression Id. */
  int TRound = 5;
  /** RegularExpression Id. */
  int TRandom = 6;
  /** RegularExpression Id. */
  int TTam = 7;
  /** RegularExpression Id. */
  int TClase = 8;
  /** RegularExpression Id. */
  int TFClase = 9;
  /** RegularExpression Id. */
  int TExtends = 10;
  /** RegularExpression Id. */
  int TPublico = 11;
  /** RegularExpression Id. */
  int TPrivado = 12;
  /** RegularExpression Id. */
  int TProtegido = 13;
  /** RegularExpression Id. */
  int TPrograma = 14;
  /** RegularExpression Id. */
  int TFPrograma = 15;
  /** RegularExpression Id. */
  int TAccionPrincipal = 16;
  /** RegularExpression Id. */
  int TFAccion = 17;
  /** RegularExpression Id. */
  int TAccion = 18;
  /** RegularExpression Id. */
  int TFuncion = 19;
  /** RegularExpression Id. */
  int TFFuncion = 20;
  /** RegularExpression Id. */
  int TRetornar = 21;
  /** RegularExpression Id. */
  int TRegistro = 22;
  /** RegularExpression Id. */
  int TFRegistro = 23;
  /** RegularExpression Id. */
  int TTipo = 24;
  /** RegularExpression Id. */
  int TComo = 25;
  /** RegularExpression Id. */
  int TDe = 26;
  /** RegularExpression Id. */
  int TLogico = 27;
  /** RegularExpression Id. */
  int TEntero = 28;
  /** RegularExpression Id. */
  int TReal = 29;
  /** RegularExpression Id. */
  int TCaracter = 30;
  /** RegularExpression Id. */
  int TCadena = 31;
  /** RegularExpression Id. */
  int TArreglo = 32;
  /** RegularExpression Id. */
  int TSubrango = 33;
  /** RegularExpression Id. */
  int TDotDotDot = 34;
  /** RegularExpression Id. */
  int TEnumerado = 35;
  /** RegularExpression Id. */
  int TLeer = 36;
  /** RegularExpression Id. */
  int TEscribir = 37;
  /** RegularExpression Id. */
  int TNuevo = 38;
  /** RegularExpression Id. */
  int TMientras = 39;
  /** RegularExpression Id. */
  int THacer = 40;
  /** RegularExpression Id. */
  int TFMientras = 41;
  /** RegularExpression Id. */
  int TRepetir = 42;
  /** RegularExpression Id. */
  int THasta = 43;
  /** RegularExpression Id. */
  int TSeleccion = 44;
  /** RegularExpression Id. */
  int TFSeleccion = 45;
  /** RegularExpression Id. */
  int TPara = 46;
  /** RegularExpression Id. */
  int TEn = 47;
  /** RegularExpression Id. */
  int TFPara = 48;
  /** RegularExpression Id. */
  int TSi = 49;
  /** RegularExpression Id. */
  int TFSi = 50;
  /** RegularExpression Id. */
  int TSino = 51;
  /** RegularExpression Id. */
  int TEntonces = 52;
  /** RegularExpression Id. */
  int TVerdad = 53;
  /** RegularExpression Id. */
  int TFalso = 54;
  /** RegularExpression Id. */
  int TEq = 55;
  /** RegularExpression Id. */
  int OpEq = 56;
  /** RegularExpression Id. */
  int OpNeq = 57;
  /** RegularExpression Id. */
  int OpLt = 58;
  /** RegularExpression Id. */
  int OpLe = 59;
  /** RegularExpression Id. */
  int OpGt = 60;
  /** RegularExpression Id. */
  int OpGe = 61;
  /** RegularExpression Id. */
  int OpAdd = 62;
  /** RegularExpression Id. */
  int OpSub = 63;
  /** RegularExpression Id. */
  int OpMul = 64;
  /** RegularExpression Id. */
  int OpMod = 65;
  /** RegularExpression Id. */
  int OpDiv = 66;
  /** RegularExpression Id. */
  int OpFDiv = 67;
  /** RegularExpression Id. */
  int OpPow = 68;
  /** RegularExpression Id. */
  int OpFalse = 69;
  /** RegularExpression Id. */
  int LOpenBracket = 70;
  /** RegularExpression Id. */
  int ROpenBracket = 71;
  /** RegularExpression Id. */
  int TDot = 72;
  /** RegularExpression Id. */
  int TComma = 73;
  /** RegularExpression Id. */
  int TConstante = 74;
  /** RegularExpression Id. */
  int LClosedBracket = 75;
  /** RegularExpression Id. */
  int RClosedBracket = 76;
  /** RegularExpression Id. */
  int LBrace = 77;
  /** RegularExpression Id. */
  int RBrace = 78;
  /** RegularExpression Id. */
  int TSemicolon = 79;
  /** RegularExpression Id. */
  int TColon = 80;
  /** RegularExpression Id. */
  int OpOr = 81;
  /** RegularExpression Id. */
  int OpAnd = 82;
  /** RegularExpression Id. */
  int alfa = 83;
  /** RegularExpression Id. */
  int digito = 84;
  /** RegularExpression Id. */
  int signo = 85;
  /** RegularExpression Id. */
  int exponente = 86;
  /** RegularExpression Id. */
  int cint = 87;
  /** RegularExpression Id. */
  int id = 88;
  /** RegularExpression Id. */
  int cfloat = 89;
  /** RegularExpression Id. */
  int character = 90;
  /** RegularExpression Id. */
  int string = 91;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 100;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT1 = 1;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<TNull>",
    "<TSelf>",
    "\"raiz\"",
    "\"techo\"",
    "\"redondear\"",
    "\"aleatorio\"",
    "\"tam\"",
    "\"Clase\"",
    "\"FClase\"",
    "\"Hereda de\"",
    "\"Publico\"",
    "\"Privado\"",
    "\"Protegido\"",
    "\"Programa\"",
    "\"FPrograma\"",
    "\"Accion Principal\"",
    "\"FAccion\"",
    "\"Accion\"",
    "\"Funcion\"",
    "\"FFuncion\"",
    "\"Retornar\"",
    "\"Registro\"",
    "\"FRegistro\"",
    "\"Tipo\"",
    "\"Como\"",
    "\"De\"",
    "\"Logico\"",
    "\"Entero\"",
    "\"Real\"",
    "\"Caracter\"",
    "\"Cadena\"",
    "\"Arreglo\"",
    "\"Subrango\"",
    "\"...\"",
    "\"Enumerado\"",
    "\"Leer\"",
    "\"Escribir\"",
    "<TNuevo>",
    "\"Mientras\"",
    "\"Hacer\"",
    "\"FMientras\"",
    "\"Repetir\"",
    "\"Hasta\"",
    "\"Seleccion\"",
    "\"FSeleccion\"",
    "\"Para\"",
    "\"En\"",
    "\"FPara\"",
    "\"Si\"",
    "\"Fsi\"",
    "\"Sino\"",
    "\"Entonces\"",
    "<TVerdad>",
    "\"falso\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"Mod\"",
    "\"Div\"",
    "\"/\"",
    "\"^\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"Constante\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "<alfa>",
    "<digito>",
    "<signo>",
    "<exponente>",
    "<cint>",
    "<id>",
    "<cfloat>",
    "<character>",
    "<string>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "<token of kind 97>",
    "\"*/\"",
    "\"#\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 101>",
  };

}
